import type { Product } from "@/types/product";

export const TESTIMONIALS = [
  {
    id: "1",
    name: "Arjun Sharma",
    role: "Competitive Bodybuilder",
    city: "Mumbai",
    rating: 5,
    text: "Fusion Nutrition's Advance Whey is hands down the cleanest protein I've used. 26g protein, zero bloating, and the Mawa Kulfi flavour is absolutely next level. Gains have been consistent for 6 months straight.",
    avatar: "AS",
    product: "Advance Whey Protein",
  },
  {
    id: "2",
    name: "Priya Nair",
    role: "CrossFit Athlete",
    city: "Bangalore",
    rating: 5,
    text: "Bull Power Pre-Workout is absolutely insane. The focus it gives me during WODs is unlike anything I've tried. No crash, no jitters — just pure sustained energy. I go with the Pinago flavour every time.",
    avatar: "PN",
    product: "Bull Power Pre-Workout",
  },
  {
    id: "3",
    name: "Rohan Mehta",
    role: "Marathon Runner",
    city: "Delhi",
    rating: 5,
    text: "Started using the Recovery EAA+BCAA during my long runs. Recovery is dramatically faster and I'm hitting PRs consistently. The Kimachee flavour is something else — genuinely refreshing mid-run.",
    avatar: "RM",
    product: "Recovery EAA+BCAA+Glutamine",
  },
  {
    id: "4",
    name: "Kavya Reddy",
    role: "Yoga & Strength Coach",
    city: "Hyderabad",
    rating: 5,
    text: "The Essential Multi Vitamin Pro has been a game changer for my energy levels and immunity. I recommend it to every single one of my clients. The ingredient profile is clean and transparent.",
    avatar: "KR",
    product: "Essential Multi Vitamin Pro",
  },
  {
    id: "5",
    name: "Vikram Singh",
    role: "Powerlifter",
    city: "Chandigarh",
    rating: 5,
    text: "Silent Power Pre-Workout is deceptively strong. The Watermelon flavour is clean and the pump it delivers mid-session is incredible. No anxiety, no crash. This brand knows their stuff.",
    avatar: "VS",
    product: "Silent Power Pre-Workout",
  },
];
